name: Build Application
on:
  push:
    branches:
      - master

jobs:
  build_on_mac:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
        os: [ macOS-latest, macOS-latest-large ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup node-gyp dependent tools
        run: brew install python-setuptools

      - name: Install dependencies
        run: pnpm i

      - name: Build
        id: build
        env:
          GITHUB_TAG: ${{ github.sha }}
          GITHUB_MATRIX_OS_NAME: ${{ matrix.os }}
        run: |
          pnpm build:mac
          new_file_name=`node ./scripts/publish_prepare.js`
          echo "::set-output name=file_name::$new_file_name"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ steps.build.outputs.file_name }}
