name: Build Application
on:
  push:
    branches:
      - master

jobs:
  build_on_mac:
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-latest, macos-latest-large ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run:  pnpm install --no-frozen-lockfile && node scripts/bootstrap.mjs

      - name: Build
        run: pnpm build:mac

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mac-${{ matrix.os }}
          path: dist/spirit-*.dmg
