name: Build Application
on:
  push:
    branches:
      - master

jobs:
  build_on_mac:
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-latest, macOS-latest-large ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          brew install python-setuptools
          pnpm i

      - name: Build
        run: |
          pnpm build:mac
          declare -A os_to_suffix
          os_to_suffix=(
            ["macOS-latest"]=".apple.dmg"
            ["macOS-latest-large"]=".intel.dmg"
          )
          platform=${{ matrix.os }}
          suffix=${os_to_suffix[$platform]}
          for file in dist/spirit-*
          do
            mv "$file" "${file%.dmg}$suffix"
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: dist/spirit-*.dmg
